"""empty message

Revision ID: 05c30968dc9b
Revises: 99532bc76535
Create Date: 2022-03-19 21:06:09.935674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c30968dc9b'
down_revision = '99532bc76535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_profiles', sa.Column('mimetype', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_profiles', 'mimetype')
    # ### end Alembic commands ###
