"""empty message

Revision ID: 44625f98b003
Revises: ec38512eb0cf
Create Date: 2022-03-19 16:31:08.441801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44625f98b003'
down_revision = 'ec38512eb0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_profiles', 'photo',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_profiles', 'photo',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
