"""empty message

Revision ID: 8534ec82c6fd
Revises: 05c30968dc9b
Create Date: 2022-03-19 22:37:34.984659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8534ec82c6fd'
down_revision = '05c30968dc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_profiles', 'img',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_profiles', 'img',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
