"""empty message

Revision ID: 8832881c81aa
Revises: b519f7891102
Create Date: 2022-03-19 19:27:08.674862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8832881c81aa'
down_revision = 'b519f7891102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_profiles', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_profiles', sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
