"""empty message

Revision ID: 99532bc76535
Revises: f0213df7371c
Create Date: 2022-03-19 20:40:41.742285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99532bc76535'
down_revision = 'f0213df7371c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_profiles', 'mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_profiles', sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
