"""empty message

Revision ID: 99fe7c29b4d7
Revises: 8534ec82c6fd
Create Date: 2022-03-19 22:55:00.981036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fe7c29b4d7'
down_revision = '8534ec82c6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_profiles', 'img',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_profiles', 'img',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
