"""empty message

Revision ID: b519f7891102
Revises: 44625f98b003
Create Date: 2022-03-19 19:20:22.522847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b519f7891102'
down_revision = '44625f98b003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_profiles', sa.Column('img', sa.Text(), nullable=False))
    op.add_column('property_profiles', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('property_profiles', sa.Column('mimetype', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'property_profiles', ['img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_profiles', type_='unique')
    op.drop_column('property_profiles', 'mimetype')
    op.drop_column('property_profiles', 'name')
    op.drop_column('property_profiles', 'img')
    # ### end Alembic commands ###
