"""empty message

Revision ID: ca5aa8dbd161
Revises: 99fe7c29b4d7
Create Date: 2022-03-19 23:39:07.539480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5aa8dbd161'
down_revision = '99fe7c29b4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_profiles', 'img',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('property_profiles', 'name')
    op.drop_column('property_profiles', 'mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_profiles', sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('property_profiles', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('property_profiles', 'img',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
