"""empty message

Revision ID: f0213df7371c
Revises: 8832881c81aa
Create Date: 2022-03-19 20:17:57.972712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0213df7371c'
down_revision = '8832881c81aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_profiles_img_key', 'property_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('property_profiles_img_key', 'property_profiles', ['img'])
    # ### end Alembic commands ###
